### ISSUE TITLE
pluralise() docs update for pluralisation of decimal numbers

### ISSUE THREAD

**Issue by charliejhadley** [cararthompson/verbaliseR#1]
`{verbaliseR}` taught me that decimal numbers should always be pluralised even if the integer component is zero (https://english.stackexchange.com/a/2148) as it currently behaves:

```r
verbaliseR::pluralise("penguin", 0.1)
#> Warning in num_to_text(number = count, sentence_start = sentence_start, : 0.1 is
#> not a whole number. It is kept as a numeral.
#> [1] "0.1 penguins"
```

However, the docs page for `pluralise()` suggests this behaviour isn't true

```
Arguments
word      A word which should be returned as plural if count is equal to 0 or greater than 1.
```

**Comment by cararthompson** [comment]
Ah, good spot, thank you!

**Comment by cararthompson** [comment]
That's it fixed. Thanks for the feedback!
